jobs: 
  main:
    current:
      scripts:
        - filePath:  current.kql
    target:
      scripts:
        - filePath:  target.kql
    action:
      filePath:  outputs/one-to-two-with-change.kql
      usePluralForms:  true
